kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jaeger-operator-for-search
  namespace: search
subjects:
- kind: ServiceAccount
  name: jaeger-operator
  namespace: search-tools
roleRef:
  kind: Role
  name: jaeger-operator-monitor
  apiGroup: rbac.authorization.k8s.io
