apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jaeger-operator-monitor
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - list
- apiGroups:
  - jaegertracing.io
  resources:
  - jaegers
  verbs:
  - get
  - list
  - update
  - watch